# Copyright (c) 2016-2024 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: "CE Platform Engineer Bootcamp"
site_url: https://github.ibm.com/skol/pe-bootcamp
site_author: John Webb
site_description: >-
    This bootcamp is designed to build on the techniques and skills for Platform Engineers during their enablement journey.  creates a merger of the previous Cloud Native Bootcamp and OCP Install Cohort experiences.

# Repository
repo_name: skol/pe-bootcamp/
repo_url: https://github.ibm.com/skol/pe-bootcamp

# Copyright
copyright: Copyright © 2025 IBM Client Engineering

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
  #  - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  favicon: https://www.ibm.com/favicon.ico
  icon:
    logo: octicons/home-16

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  # homepage: pe/index.md

  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/squidfunk
  #   - icon: fontawesome/brands/docker
  #     link: https://hub.docker.com/r/squidfunk/mkdocs-material/
  #   - icon: fontawesome/brands/python
  #     link: https://pypi.org/project/mkdocs-material/
  #   - icon: fontawesome/brands/mastodon
  #     link: https://fosstodon.org/@squidfunk
  #   - icon: fontawesome/brands/x-twitter
  #     link: https://x.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: skol
      repo: pe-bootcamp
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Welcome: 
    - index.md
    - Agenda: agenda.md
    - Workstation Setup: workstation-setup.md
  - Cloud Native:
    - cn/index.md
    - Learn - Intro to Cloud Native: cn/cloud-native.md
    - Learn - App Dev: cn/app-dev.md
    - Learn - Containers: cn/containers.md
    - Container Quick Reference: cn/reference.md
    - Lab CN 1 - Image Registries: cn/imageregistry.md
    - Lab CN 2 - Podman: cn/podman.md
    - Lab CN 3 - Running a Container Locally: cn/running-containers.md
  - Kubernetes & OpenShift:
    - k8s/openshift/index.md
    - Learn - API Primitives: k8s/openshift/core-concepts/index.md
    - Learn - Namespaces & Projects: k8s/openshift/core-concepts/namespaces-projects/index.md
    - Learn - Pod Basics: k8s/openshift/pods/index.md
    - Learn - Labels-Selectors: k8s/openshift/pods/tagging/index.md
    - Lab K8s 1 - Pod Creation: k8s/pod-creation.md
    - Learn - Multi-Container: k8s/openshift/pods/multi-container/index.md
    - Lab K8s 2 - Multiple Containers: k8s/multi-containers.md
    - Learn - Health & Monitoring: k8s/openshift/pods/health-checks/index.md
    - Lab K8s 3 - Probes: k8s/probes.md
    - Learn - Troubleshooting: k8s/openshift/pods/troubleshooting/index.md
    - Lab K8s 4 - Troubleshooting: k8s/debugging.md
    - Learn - Configuration: k8s/openshift/configuration/index.md
    - Learn - Config Maps: k8s/openshift/configuration/config-map/index.md
    - Learn - Secrets: k8s/openshift/configuration/secrets/index.md
    - Learn - Security Contexts: k8s/openshift/configuration/security-contexts/index.md
    - Learn - Service Accounts: k8s/openshift/configuration/service-accounts/index.md
    - Lab K8s 5 - Pod Configuration: k8s/pod-config.md
    - Learn - Deployments: k8s/openshift/deployments/index.md
    - Learn - Rolling Updates: k8s/openshift/deployments/updates/index.md
    - Lab K8s 6 - Rolling Updates: k8s/rolling-updates.md
    - Learn - Jobs & CronJobs: k8s/openshift/pods/jobs/index.md
    - Lab K8s 7 - Cron Jobs: k8s/cron-jobs.md
    - Learn - Networking: k8s/openshift/services-networking/index.md
    - Learn - Services: k8s/openshift/services-networking/services.md
    - Learn - Routes: k8s/openshift/services-networking/routes.md
    - Lab K8s 8 - Creating Services: k8s/creating-services.md
    - Lab K8s 9 - Network Policies: k8s/network-policies.md
    - Learn - Ingresses: k8s/openshift/services-networking/ingress.md
    - Learn - State Persistence: k8s/openshift/state-persistence/index.md
    - Learn - Volumes: k8s/openshift/state-persistence/volumes.md
    - Learn - Persistent Volumes & Claims: k8s/openshift/state-persistence/pv-pvc.md
    - Lab K8s 10 - Persistent Volumes: k8s/persistent-volumes.md
    - Reference - K8s Lab Solutions: k8s/cheats.md
  - DevOps & GitOps:
    - devops/index.md
    - Learn CI: devops/tekton/index.md
    - Lab CI 1 - Tekton: devops/tekton/tekton.md
#    - Learn IBM ToolChain: devops/ibm-toolchain/index.md
#    - Lab CI 2 - Tekton on IBM Cloud: devops/ibm-toolchain/ibm-toolchain.md
#    - Lab CI 3 - Jenkins: devops/jenkins/jenkins.md
    - Learn CD: devops/argocd/index.md
#    - Walkthrough - GitOps & OCP: devops/gitops-ocp.md
    - Lab CD 1 - ArgoCD: devops/argocd/argocd.md
  - HashiCorp:
    - Terraform 101:  terraform/index.md
    - Terraform VSphere Lab:  terraform/terraform-vsphere-lab.md
  - IBM Concert:
    - concert/index.md
    - Concert SBOM Lab: concert/concert-sbom.md
    - Concert Workflows Lab: concert/concert-workflows.md
  - Integration:
    - integration/index.md
    - CP4I Prereqs: integration/01-prereqs.md
    - CP4I Base: integration/02-base-deploy.md
    - APIC: integration/03-apic.md
    - Event Automation: integration/04-event-automation.md
    - Messaging: integration/05-mq.md
    - App Connect: integration/06-ace.md
    - Additional Steps: integration/07-demo-config.md
    - Other Integration Prereqs: integration/tech-jam-labs/prereq-general.md
    - Optional Lab - MQ: integration/tech-jam-labs/mq.md
    - Optional Lab - Event Streams: integration/tech-jam-labs/event-streams.md
    - Optional Lab - ACE Prereqs: integration/tech-jam-labs/prereq-ace-toolkit.md
    - Optional Lab - ACE & MQ Node: integration/tech-jam-labs/ace-mq.md
    - Optional Lab - ACE & Kafka: integration/tech-jam-labs/ace-es.md
    - Optional Lab - APIC for Dev: integration/tech-jam-labs/apic-prep.md
    - Optional Lab - APIC Develop: integration/tech-jam-labs/apic-dev.md
    - Optional Lab - APIC Consume: integration/tech-jam-labs/apic-consume.md
    - Optional Lab - APIC Analyze: integration/tech-jam-labs/apic-analyze.md
  - Deploying OpenShift: 
    #- Cloud Native Challenge: cn-challenge/index.md
    - Deploying OpenShift on IBM Cloud: 
      - ocp-on-ibm-cloud/index.md
      - Prepare for Installation: ocp-on-ibm-cloud/prepare.md
      - Install the Cluster: ocp-on-ibm-cloud/install-cluster.md
      - Backup etcd: ocp-on-ibm-cloud/backup-etcd.md
    - Deploying OpenShift on VMware: 
      - ocp-on-vmware/index.md
      - Prepare for Installation: ocp-on-vmware/prepare.md
      - Create the Install Config Asset: ocp-on-vmware/create-install-config.md
      - Install the Cluster: ocp-on-vmware/install-cluster.md
      - Configure the Identity Provider: ocp-on-vmware/config-identity-provider.md
      - Install OpenShift Data Foundation: ocp-on-vmware/install-data-foundation.md
      - Configure Internal Image Registry: ocp-on-vmware/config-image-registry.md
      - Add IBM Software Entitlement: ocp-on-vmware/update-global-pull-secret.md
    - Deploying Air-Gapped OpenShift on VMware: 
      - ocp-on-vmware-airgapped/index.md
      - Setup the mirror host: ocp-on-vmware-airgapped/mirror-host.md
      - Mirror OpenShift Content: ocp-on-vmware-airgapped/mirror.md
      - Prepare the Installation: ocp-on-vmware-airgapped/prepare-installation.md
      - Disable Internet access: ocp-on-vmware-airgapped/disable-internet.md
      - Create Install Config: ocp-on-vmware-airgapped/install-config.md
      - Install the Cluster: ocp-on-vmware-airgapped/install-cluster.md
      - Install ODF: ocp-on-vmware-airgapped/install-odf.md
    - Deploying Air-Gapped OpenShift:
      - Solution Architecture: airgapped/1-solution.md
      - Infrastructure Services: airgapped/2-infraservices.md
      - Network Configuration: airgapped/3-networkconfig.md
      - DNS Server Entries: airgapped/4-dnsserverentries.md
      - Load Balancer Configuration: airgapped/5-lbconfig.md
      - VPN Configuration: airgapped/6-vpnconfig.md
      - Guacamole VM: airgapped/7-guacamolevm.md
      - Bastion Nodes: airgapped/8-bastionnodes.md
      - Configure Online Bastion: airgapped/9-onlinebastion.md
      - Configure Offline Bastion: airgapped/10-offlinebastion.md
      - Create custom Red Hat CoreOS ISO: airgapped/11-coreosisomaker.md
      - Create OpenShift VMs: airgapped/12-createocpvms.md
      - Create OpenShift Install Config: airgapped/13-createocpinstallconfig.md
      - Create OCP Manifests & Ignition Config: airgapped/14-createocpmanifests.md
      - Deploy OpenShift Cluster: airgapped/15-deployocpcluster.md
      - Configure Infra Nodes: airgapped/16-configinfranodes.md
      - Day 2 Operations: airgapped/17-day2ops.md 
      - Configure Storage Nodes: airgapped/18-configstoragenodes.md
      - Success: airgapped/success.md
