# Copyright (c) 2016-2024 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: "CE Platform Engineer Bootcamp"
site_url: https://github.ibm.com/skol/pe-bootcamp
site_author: John Webb
site_description: >-
    This bootcamp is designed to build on the techniques and skills for Platform Engineers during their enablement journey.  creates a merger of the previous Cloud Native Bootcamp and OCP Install Cohort experiences.

# Copyright
copyright: Copyright © 2025 IBM Client Engineering

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
  #  - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  favicon: https://www.ibm.com/favicon.ico
  icon:
    logo: octicons/home-16

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  # homepage: pe/index.md

  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/squidfunk
  #   - icon: fontawesome/brands/docker
  #     link: https://hub.docker.com/r/squidfunk/mkdocs-material/
  #   - icon: fontawesome/brands/python
  #     link: https://pypi.org/project/mkdocs-material/
  #   - icon: fontawesome/brands/mastodon
  #     link: https://fosstodon.org/@squidfunk
  #   - icon: fontawesome/brands/x-twitter
  #     link: https://x.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: skol
      repo: ce-platform-engineering
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Welcome: 
    - index.md
  - Deploying OpenShift on VMware: 
    - ocp-on-vmware/index.md
    - Prepare for Installation: ocp-on-vmware/prepare.md
    - Create the Install Config Asset: ocp-on-vmware/create-install-config.md
    - Install the Cluster: ocp-on-vmware/install-cluster.md
    - Configure the Identity Provider: ocp-on-vmware/config-identity-provider.md
    - Install OpenShift Data Foundation: ocp-on-vmware/install-data-foundation.md
    - Configure INternal Image Registry: ocp-on-vmware/config-image-registry.md
  - Installing OpenShift on IBM Cloud: 
    - ocp-on-ibm-cloud/index.md
    - Prepare for Installation: ocp-on-ibm-cloud/prepare.md
    - Install the Cluster: ocp-on-ibm-cloud/install-cluster.md
    - Backup etcd: ocp-on-ibm-cloud/backup-etcd.md
  - Cloud Native & Containers:
    - cn/index.md
    - Learn - Intro to Cloud Native: cn/cloud-native.md
    - Learn - App Dev: cn/app-dev.md
    - Learn - Containers: cn/containers.md
    - Reference - Helpful Information: cn/reference.md
    - Reference - Image Registries: cn/imageregistry.md
    - Lab - Docker: cn/containers.md
    - Lab - Container Registries: cn/ibm-registries.md
  - K8s & OpenShift:
    - k8s/index.md
    - Learn - Kubernetes: k8s/openshift/index.md
    - Lab K8s 1 - Pod Creation: k8s/pod-creation.md
    - Lab K8s 2 - Pod Configuration: k8s/pod-config.md
    - Lab K8s 3 - Multiple Containers: k8s/multi-containers.md
    - Lab K8s 4 - Probes: k8s/probes.md
    - Lab K8s 5 - Debugging: k8s/debugging.md
    - Lab K8s 6 - Rolling Updates: k8s/rolling-updates.md
    - Lab K8s 7 - Cron Jobs: k8s/cron-jobs.md
    - Lab K8s 8 - Creating Services: k8s/creating-services.md
    - Lab K8s 9 - Network Policies: k8s/network-policies.md
    - Lab K8s 10 - Persistent Volumes: k8s/persistent-volumes.md
    - Lab K8s 11 - Ingress IKS: k8s/ingress.md
    - Reference - K8s Lab Solutions: k8s/cheats.md
  - Continuous Integration:
    - ci/index.md
    - Walkthrough - S2I: ci/s2i.md
    - Lab - Tekton: ci/tekton.md
    - Lab - Tekton on IBM Cloud: ci/tekton-ibm-cloud.md
    - Lab - Jenkins: ci/jenkins.md
  - Continuous Deployment:
    - cd/index.md
    - Walkthrough - GitOps & OCP: cd/gitops-ocp.md
    - Walkthrough - GitOps Multi-Cluster: cd/gitops-multi-cluster.md
    - Lab - ArgoCD: cd/argocd.md
  - Cloud Native Challenge (Optional): 
    - cn-challenge/index.md

  